version: '3'
services:
  db:
    image: postgres:14.4-alpine
    container_name: postgres_conteiner
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=testdb